-- -------------------------------------------------------------------------------------------------
-- Copyright (c) Lukas Vik. All rights reserved.
--
-- This file is part of the hdl-modules project, a collection of reusable, high-quality,
-- peer-reviewed VHDL building blocks.
-- https://hdl-modules.com
-- https://github.com/hdl-modules/hdl-modules
-- -------------------------------------------------------------------------------------------------
-- Generic, parameterizable, register file for AXI-Lite register buses.
-- Is parameterizable via a generic that sets the list of registers, with their modes and their
-- default values.
--
-- The ``regs`` and ``default_values`` generics are designed to get their values
-- from a package generated by the :external:ref:`hdl-registers VHDL generator <generator_vhdl>`.
-- The values can be constructed by hand as well, of course.
--
--
-- Error handling
-- ______________
--
-- Will respond with ``SLVERR`` on the ``R`` channel when attempting to read a register that
--
-- 1. Does not exists (``ARADDR`` out of range), or
-- 2. Is not of a register type that can be read by the bus (e.g. write only).
--
-- Similarly, it will respond with ``SLVERR`` on the ``B`` channel when attempting to write a
-- register that
--
-- 1. Does not exists (``AWADDR`` out of range), or
-- 2. Is not of a register type that can be written by the bus (e.g. read only).
--
-- Both cases are handled cleanly without stalling or hanging the AXI-Lite bus.
--
--
-- Reset
-- _____
--
-- This entity features an active-high synchronous reset.
-- The reset signal is not required to be connected, as the code uses initial values for
-- all registers.
-- It can be safe to leave it unconnected and tied to zero.
--
-- If the reset is asserted, however, the AXI-Lite handshaking state will be reset as well as
-- all register values.
-- -------------------------------------------------------------------------------------------------

-- vsg_off
-- Vendored verbatim from hdl-modules (see header above); identifiers keep upstream naming
-- instead of this repo's s_/t_/c_ prefix convention, to stay diffable against upstream.

LIBRARY IEEE;
  USE ieee.std_logic_1164.ALL;
  USE ieee.numeric_std.ALL;

-- axi_lite_pkg and register_file_pkg both live in this repo's single flat "lib" library
  USE work.axi_lite_pkg.ALL;
  USE work.register_file_pkg.ALL;


ENTITY axi_lite_register_file IS
  GENERIC (
    registers : register_definition_vec_t;
    default_values : register_vec_t(registers'RANGE) := (OTHERS => (OTHERS => '0'))
  );
  PORT (
    clk : IN std_ulogic;
    -- Active-high synchronous reset.
    -- The code in this entity uses initial values so an initial reset is NOT necessary.
    -- This port can safely be left unconnected and tied to zero.
    -- If asserted, it will reset the AXI-Lite handshaking state as well as all register values.
    reset : IN std_ulogic := '0';
    --# {{}}
    --# Register control bus
    axi_lite_m2s : IN axi_lite_m2s_t;
    axi_lite_s2m : OUT axi_lite_s2m_t := axi_lite_s2m_init;
    --# {{}}
    -- Register values
    regs_up : IN register_vec_t(registers'RANGE) := default_values;
    regs_down : OUT register_vec_t(registers'RANGE) := default_values;
    --# {{}}
    -- Each bit is pulsed for one cycle when the corresponding register is read/written.
    -- For read, the bit is asserted the exact same cycle as the AXI-Lite R transaction occurs.
    -- For write, the bit is asserted the cycle after the AXI-Lite W transaction occurs, so that
    -- 'regs_down' is updated with the new value.
    reg_was_read : OUT std_ulogic_vector(registers'RANGE) := (OTHERS => '0');
    reg_was_written : OUT std_ulogic_vector(registers'RANGE) := (OTHERS => '0')
  );
END ENTITY;

ARCHITECTURE a OF axi_lite_register_file IS

  CONSTANT num_address_bits : positive := num_address_bits_needed(registers=> registers);
  SUBTYPE address_range IS natural RANGE num_address_bits + 2 - 1 DOWNTO 2;

  SIGNAL reg_values : register_vec_t(registers'RANGE) := default_values;

BEGIN

  ------------------------------------------------------------------------------
  assign_down : PROCESS (ALL)
  BEGIN
    -- Assign only the bits that are marked as utilized, so there is no risk of confusion/misuse.
    FOR reg_idx IN registers'RANGE LOOP
      IF is_write_mode(registers(reg_idx).mode) THEN
        regs_down(reg_idx)(registers(reg_idx).utilized_width - 1 DOWNTO 0) <= reg_values(reg_idx)(
          registers(reg_idx).utilized_width - 1 DOWNTO 0
        );
      END IF;
    END LOOP;
  END PROCESS;


  ------------------------------------------------------------------------------
  read_block : BLOCK
    TYPE read_state_t IS (AR, R);
    SIGNAL read_state : read_state_t := AR;
    SIGNAL read_index : u_unsigned(num_address_bits - 1 DOWNTO 0) := (OTHERS => '0');
  BEGIN

    ------------------------------------------------------------------------------
    set_status : PROCESS (ALL)
    BEGIN
      reg_was_read <= (OTHERS => '0');

      axi_lite_s2m.read.r.resp <= axi_lite_resp_slverr;

      -- Set initial values zero.
      -- Below we will only assign the bits that are actually utilized by the register.
      -- Hopefully, software should not look at any bits outside of the utilized width,
      -- but set zero just in case and to avoid confusion.
      -- Does not impact netlist build size.
      axi_lite_s2m.read.r.data(reg_values(0)'RANGE) <= (OTHERS => '0');

      FOR list_idx IN registers'RANGE LOOP
        IF is_read_mode(registers(list_idx).mode) THEN
          IF read_index = list_idx THEN
            axi_lite_s2m.read.r.resp <= axi_lite_resp_okay;
            reg_was_read(list_idx) <= axi_lite_m2s.read.r.ready AND axi_lite_s2m.read.r.valid;
          END IF;

          FOR bit_idx IN 0 TO registers(list_idx).utilized_width - 1 LOOP
            IF is_application_gives_value_mode(registers(list_idx).mode) THEN
              IF read_index = list_idx THEN
                axi_lite_s2m.read.r.data(bit_idx) <= regs_up(list_idx)(bit_idx);
              END IF;
            ELSE
              IF read_index = list_idx THEN
                axi_lite_s2m.read.r.data(bit_idx) <= reg_values(list_idx)(bit_idx);
              END IF;
            END IF;
          END LOOP;
        END IF;
      END LOOP;
    END PROCESS;


    ------------------------------------------------------------------------------
    read_process : PROCESS
    BEGIN
      WAIT UNTIL rising_edge(clk);

      CASE read_state IS
        WHEN AR =>
          -- Sample always, will only be used if we change state.
          read_index <= axi_lite_m2s.read.ar.addr(address_range);

          axi_lite_s2m.read.ar.ready <= '1';

          IF axi_lite_s2m.read.ar.ready AND axi_lite_m2s.read.ar.valid THEN
            axi_lite_s2m.read.ar.ready <= '0';

            read_state <= R;
          END IF;

        WHEN R =>
          axi_lite_s2m.read.r.valid <= '1';

          IF axi_lite_m2s.read.r.ready AND axi_lite_s2m.read.r.valid THEN
            axi_lite_s2m.read.r.valid <= '0';
            axi_lite_s2m.read.ar.ready <= '1';

            read_state <= AR;
          END IF;
      END CASE;

      IF reset THEN
        read_state <= AR;

        axi_lite_s2m.read.ar.ready <= '0';
        axi_lite_s2m.read.r.valid <= '0';
      END IF;
    END PROCESS;

  END BLOCK;


  ------------------------------------------------------------------------------
  write_block : BLOCK
    TYPE write_state_t IS (AW, W, B);
    SIGNAL write_state : write_state_t := AW;
    SIGNAL write_index : u_unsigned(num_address_bits - 1 DOWNTO 0) := (OTHERS => '0');
  BEGIN

    ------------------------------------------------------------------------------
    set_status : PROCESS
    BEGIN
      WAIT UNTIL rising_edge(clk);

      reg_was_written <= (OTHERS => '0');

      axi_lite_s2m.write.b.resp <= axi_lite_resp_slverr;

      FOR list_idx IN registers'RANGE LOOP
        IF is_write_pulse_mode(registers(list_idx).mode) THEN
          FOR bit_idx IN 0 TO registers(list_idx).utilized_width - 1 LOOP
            -- Set initial default value.
            -- If a write occurs to this register, the value will be asserted for one cycle below.
            reg_values(list_idx)(bit_idx) <= default_values(list_idx)(bit_idx);
          END LOOP;
        END IF;
      END LOOP;

      FOR list_idx IN registers'RANGE LOOP
        IF is_write_mode(registers(list_idx).mode) THEN
          IF write_index = list_idx THEN
            axi_lite_s2m.write.b.resp <= axi_lite_resp_okay;
            reg_was_written(list_idx) <= axi_lite_s2m.write.w.ready AND axi_lite_m2s.write.w.valid;
          END IF;

          FOR bit_idx IN 0 TO registers(list_idx).utilized_width - 1 LOOP
            IF write_index = list_idx THEN
              IF axi_lite_s2m.write.w.ready AND axi_lite_m2s.write.w.valid THEN
                reg_values(list_idx)(bit_idx) <= axi_lite_m2s.write.w.data(bit_idx);
              END IF;
            END IF;
          END LOOP;
        END IF;
      END LOOP;

      IF reset THEN
        reg_values <= default_values;
      END IF;
    END PROCESS;


    ------------------------------------------------------------------------------
    -- The handshaking is not really optimal, but if it is "optimized" the LUT usage increases
    -- by 100% for some reason.
    -- Leave as it is for now, might be worth investigating at some point in the future.
    write_process : PROCESS
    BEGIN
      WAIT UNTIL rising_edge(clk);

      CASE write_state IS
        WHEN AW =>
          -- Sample always, will only be used if we change state.
          write_index <= axi_lite_m2s.write.aw.addr(address_range);

          axi_lite_s2m.write.aw.ready <= '1';

          IF axi_lite_s2m.write.aw.ready AND axi_lite_m2s.write.aw.valid THEN
            axi_lite_s2m.write.aw.ready <= '0';
            axi_lite_s2m.write.w.ready <= '1';

            write_state <= W;
          END IF;

        WHEN W =>
          IF axi_lite_s2m.write.w.ready AND axi_lite_m2s.write.w.valid THEN
            axi_lite_s2m.write.w.ready <= '0';
            axi_lite_s2m.write.b.valid <= '1';

            write_state <= B;
          END IF;

        WHEN B =>
          IF axi_lite_m2s.write.b.ready AND axi_lite_s2m.write.b.valid THEN
            axi_lite_s2m.write.aw.ready <= '1';
            axi_lite_s2m.write.b.valid <= '0';

            write_state <= AW;
          END IF;
      END CASE;

      IF reset THEN
        write_state <= AW;

        axi_lite_s2m.write.aw.ready <= '0';
        axi_lite_s2m.write.w.ready <= '0';
        axi_lite_s2m.write.b.valid <= '0';
      END IF;
    END PROCESS;

  END BLOCK;

END ARCHITECTURE;
-- vsg_on
