#!/usr/bin/env python3
"""
Updates the badges/shields and test results table in README.md
based on an xUnit XML report generated by VUnit.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys
import xml.etree.ElementTree as ET


def parse_xunit(xml_path: Path):
    tree = ET.parse(xml_path)
    root = tree.getroot()

    testbenches: dict[str, list[dict]] = {}
    total = 0
    failures = 0
    errors = 0
    skipped = 0

    suites = [root] if root.tag == "testsuite" else root.findall("testsuite")
    for suite in suites:
        for case in suite.findall("testcase"):
            total += 1
            classname = case.get("classname", "unknown")
            tb_name = classname.removeprefix("lib.")
            name = case.get("name", "unknown")
            time_sec = float(case.get("time", "0.0"))

            is_fail = case.find("failure") is not None
            is_err = case.find("error") is not None
            is_skip = case.find("skipped") is not None

            if is_fail:
                failures += 1
                status = "Fail"
            elif is_err:
                errors += 1
                status = "Error"
            elif is_skip:
                skipped += 1
                status = "Skipped"
            else:
                status = "Pass"

            if tb_name not in testbenches:
                testbenches[tb_name] = []

            testbenches[tb_name].append({
                "name": name,
                "status": status,
                "time": time_sec,
            })

    total_failures = failures + errors
    passed = total - total_failures - skipped

    return {
        "total": total,
        "passed": passed,
        "failed": total_failures,
        "skipped": skipped,
        "testbenches": testbenches,
    }


def generate_shields(data: dict) -> str:
    total = data["total"]
    passed = data["passed"]
    failed = data["failed"]

    if failed == 0:
        tests_badge = f"[![Tests](https://img.shields.io/badge/tests-{passed}%20passed-brightgreen)](#test-results)"
    else:
        tests_badge = f"[![Tests](https://img.shields.io/badge/tests-{failed}%20failed%20%2F%20{total}%20total-red)](#test-results)"

    workflow_badge = "[![CI](https://github.com/monkey265/HDL-library/actions/workflows/ci.yml/badge.svg)](https://github.com/monkey265/HDL-library/actions/workflows/ci.yml)"
    simulator_badge = "[![Simulator](https://img.shields.io/badge/simulator-NVC-blue)](#nvc)"

    return f"{workflow_badge}\n{tests_badge}\n{simulator_badge}"


def generate_table(data: dict) -> str:
    total = data["total"]
    passed = data["passed"]
    failed = data["failed"]
    testbenches = data["testbenches"]

    lines: list[str] = []

    # Summary table
    lines.append("| Testbench | Tests | Passing | Failing | Status | Simulator |")
    lines.append("| :--- | :---: | :---: | :---: | :---: | :---: |")

    for tb_name in sorted(testbenches.keys()):
        cases = testbenches[tb_name]
        tb_total = len(cases)
        tb_failed = sum(1 for c in cases if c["status"] in ("Fail", "Error"))
        tb_passed = tb_total - tb_failed - sum(1 for c in cases if c["status"] == "Skipped")
        status_icon = ":white_check_mark: Pass" if tb_failed == 0 else ":x: Fail"
        lines.append(f"| `{tb_name}` | {tb_total} | {tb_passed} | {tb_failed} | {status_icon} | NVC |")

    lines.append("")
    lines.append("<details>")
    lines.append(f"<summary><b>Detailed Test Cases ({passed} passed, {failed} failed)</b></summary>")
    lines.append("")
    lines.append("| Testbench | Test Case | Status | Duration |")
    lines.append("| :--- | :--- | :---: | :---: |")

    for tb_name in sorted(testbenches.keys()):
        cases = sorted(testbenches[tb_name], key=lambda c: c["name"])
        for case in cases:
            if case["status"] == "Pass":
                icon = ":white_check_mark: Pass"
            elif case["status"] == "Skipped":
                icon = ":warning: Skipped"
            else:
                icon = ":x: Fail"
            duration = f"{case['time']:.1f}s"
            lines.append(f"| `{tb_name}` | `{case['name']}` | {icon} | {duration} |")

    lines.append("")
    lines.append("</details>")

    return "\n".join(lines)


def update_readme(readme_path: Path, xml_path: Path) -> None:
    data = parse_xunit(xml_path)
    shields_content = generate_shields(data)
    table_content = generate_table(data)

    content = readme_path.read_text(encoding="utf-8")

    shields_pattern = re.compile(
        r"<!-- SHIELDS_START -->.*?<!-- SHIELDS_END -->",
        re.DOTALL,
    )
    new_shields = f"<!-- SHIELDS_START -->\n{shields_content}\n<!-- SHIELDS_END -->"

    if shields_pattern.search(content):
        content = shields_pattern.sub(new_shields, content)
    else:
        # Place right below the top-level heading
        h1_pattern = re.compile(r"^(# [^\n]*\n)", re.MULTILINE)
        if h1_pattern.search(content):
            content = h1_pattern.sub(rf"\1\n{new_shields}\n", content, count=1)
        else:
            content = f"{new_shields}\n\n" + content

    table_pattern = re.compile(
        r"<!-- TEST_RESULTS_START -->.*?<!-- TEST_RESULTS_END -->",
        re.DOTALL,
    )
    new_table = f"<!-- TEST_RESULTS_START -->\n{table_content}\n<!-- TEST_RESULTS_END -->"

    if table_pattern.search(content):
        content = table_pattern.sub(new_table, content)
    else:
        # Add ## Test Results section before ## Running the tests if present
        running_tests_pattern = re.compile(r"(## Running the tests)", re.MULTILINE)
        section = f"## Test Results\n\n{new_table}\n\n"
        if running_tests_pattern.search(content):
            content = running_tests_pattern.sub(rf"{section}\1", content, count=1)
        else:
            content = content.rstrip() + f"\n\n## Test Results\n\n{new_table}\n"

    readme_path.write_text(content, encoding="utf-8")
    print(f"Successfully updated {readme_path} with {data['passed']}/{data['total']} tests passing.")


def main():
    parser = argparse.ArgumentParser(description="Update README.md with test results.")
    parser.add_argument("xml_path", nargs="?", default="vunit_out/xunit.xml", type=Path, help="Path to xUnit XML report")
    parser.add_argument("--readme", default="README.md", type=Path, help="Path to README.md")
    args = parser.parse_args()

    if not args.xml_path.exists():
        print(f"Error: XML report file '{args.xml_path}' not found.", file=sys.stderr)
        sys.exit(1)

    update_readme(args.readme, args.xml_path)


if __name__ == "__main__":
    main()
