#!/usr/bin/env python3
"""
Updates the badges/shields, test results table, and code coverage table in README.md
based on an xUnit XML report and optional Cobertura coverage report generated by VUnit.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys
import xml.etree.ElementTree as ET


def parse_xunit(xml_path: Path):
    tree = ET.parse(xml_path)
    root = tree.getroot()

    testbenches: dict[str, list[dict]] = {}
    total = 0
    failures = 0
    errors = 0
    skipped = 0

    suites = [root] if root.tag == "testsuite" else root.findall("testsuite")
    for suite in suites:
        for case in suite.findall("testcase"):
            total += 1
            classname = case.get("classname", "unknown")
            tb_name = classname.removeprefix("lib.")
            name = case.get("name", "unknown")
            time_sec = float(case.get("time", "0.0"))

            is_fail = case.find("failure") is not None
            is_err = case.find("error") is not None
            is_skip = case.find("skipped") is not None

            if is_fail:
                failures += 1
                status = "Fail"
            elif is_err:
                errors += 1
                status = "Error"
            elif is_skip:
                skipped += 1
                status = "Skipped"
            else:
                status = "Pass"

            if tb_name not in testbenches:
                testbenches[tb_name] = []

            testbenches[tb_name].append({
                "name": name,
                "status": status,
                "time": time_sec,
            })

    total_failures = failures + errors
    passed = total - total_failures - skipped

    return {
        "total": total,
        "passed": passed,
        "failed": total_failures,
        "skipped": skipped,
        "testbenches": testbenches,
    }


def parse_coverage(cov_xml: Path) -> dict | None:
    if not cov_xml.exists():
        return None
    try:
        tree = ET.parse(cov_xml)
        root = tree.getroot()
        line_rate = float(root.get("line-rate", "0.0")) * 100.0
        branch_rate = float(root.get("branch-rate", "0.0")) * 100.0
        lines_valid = int(root.get("lines-valid", "0"))
        lines_covered = int(root.get("lines-covered", "0"))
        branches_valid = int(root.get("branches-valid", "0"))
        branches_covered = int(root.get("branches-covered", "0"))

        files: dict[str, dict] = {}
        for cls_elem in root.findall(".//class"):
            filename = cls_elem.get("filename", "")
            base = Path(filename).name if filename else cls_elem.get("name", "unknown")
            lines = cls_elem.findall(".//line")
            tot = len(lines)
            cov = sum(1 for l in lines if int(l.get("hits", "0")) > 0)
            lr = (cov / tot * 100.0) if tot > 0 else 0.0
            br = float(cls_elem.get("branch-rate", "0.0")) * 100.0
            files[base] = {
                "lines_total": tot,
                "lines_covered": cov,
                "line_rate": lr,
                "branch_rate": br,
            }

        return {
            "line_rate": line_rate,
            "branch_rate": branch_rate,
            "lines_valid": lines_valid,
            "lines_covered": lines_covered,
            "branches_valid": branches_valid,
            "branches_covered": branches_covered,
            "files": files,
        }
    except Exception as e:
        print(f"Warning: could not parse coverage XML: {e}", file=sys.stderr)
        return None


def generate_shields(data: dict, cov_data: dict | None = None) -> str:
    total = data["total"]
    passed = data["passed"]
    failed = data["failed"]

    if failed == 0:
        tests_badge = f"[![Tests](https://img.shields.io/badge/tests-{passed}%20passed-brightgreen)](#test-results)"
    else:
        tests_badge = f"[![Tests](https://img.shields.io/badge/tests-{failed}%20failed%20%2F%20{total}%20total-red)](#test-results)"

    workflow_badge = "[![CI](https://github.com/monkey265/HDL-library/actions/workflows/ci.yml/badge.svg)](https://github.com/monkey265/HDL-library/actions/workflows/ci.yml)"
    simulator_badge = "[![Simulator](https://img.shields.io/badge/simulator-NVC-blue)](#nvc)"

    badges = [workflow_badge, tests_badge]

    if cov_data:
        lr = cov_data["line_rate"]
        if lr >= 90.0:
            cov_color = "brightgreen"
        elif lr >= 75.0:
            cov_color = "yellow"
        else:
            cov_color = "red"
        cov_badge = f"[![Coverage](https://img.shields.io/badge/coverage-{lr:.1f}%25-{cov_color})](#code-coverage)"
        badges.append(cov_badge)

    badges.append(simulator_badge)
    return "\n".join(badges)


def generate_table(data: dict) -> str:
    total = data["total"]
    passed = data["passed"]
    failed = data["failed"]
    testbenches = data["testbenches"]

    lines: list[str] = []

    # Summary table
    lines.append("| Testbench | Tests | Passing | Failing | Status | Simulator |")
    lines.append("| :--- | :---: | :---: | :---: | :---: | :---: |")

    for tb_name in sorted(testbenches.keys()):
        cases = testbenches[tb_name]
        tb_total = len(cases)
        tb_failed = sum(1 for c in cases if c["status"] in ("Fail", "Error"))
        tb_passed = tb_total - tb_failed - sum(1 for c in cases if c["status"] == "Skipped")
        status_icon = ":white_check_mark: Pass" if tb_failed == 0 else ":x: Fail"
        lines.append(f"| `{tb_name}` | {tb_total} | {tb_passed} | {tb_failed} | {status_icon} | NVC |")

    lines.append("")
    lines.append("<details>")
    lines.append(f"<summary><b>Detailed Test Cases ({passed} passed, {failed} failed)</b></summary>")
    lines.append("")
    lines.append("| Testbench | Test Case | Status | Duration |")
    lines.append("| :--- | :--- | :---: | :---: |")

    for tb_name in sorted(testbenches.keys()):
        cases = sorted(testbenches[tb_name], key=lambda c: c["name"])
        for case in cases:
            if case["status"] == "Pass":
                icon = ":white_check_mark: Pass"
            elif case["status"] == "Skipped":
                icon = ":warning: Skipped"
            else:
                icon = ":x: Fail"
            duration = f"{case['time']:.1f}s"
            lines.append(f"| `{tb_name}` | `{case['name']}` | {icon} | {duration} |")

    lines.append("")
    lines.append("</details>")

    return "\n".join(lines)


def generate_coverage_table(cov_data: dict) -> str:
    lines = [
        "| Source File | Lines | Line Coverage | Branch Coverage |",
        "| :--- | :---: | :---: | :---: |",
    ]
    files = cov_data.get("files", {})
    for name, d in sorted(files.items()):
        lines.append(
            f"| `{name}` | {d['lines_covered']} / {d['lines_total']} | {d['line_rate']:.1f}% | {d['branch_rate']:.1f}% |"
        )
    lines.append(
        f"| **Overall Total** | **{cov_data['lines_covered']} / {cov_data['lines_valid']}** | **{cov_data['line_rate']:.1f}%** | **{cov_data['branch_rate']:.1f}%** |"
    )
    return "\n".join(lines)


def update_readme(readme_path: Path, xml_path: Path, cov_path: Path | None = None) -> None:
    data = parse_xunit(xml_path)
    coverage_path = cov_path or (xml_path.parent / "coverage" / "cobertura.xml")
    cov_data = parse_coverage(coverage_path) if coverage_path.exists() else None

    shields_content = generate_shields(data, cov_data)
    table_content = generate_table(data)

    content = readme_path.read_text(encoding="utf-8")

    # Update shields
    shields_pattern = re.compile(
        r"<!-- SHIELDS_START -->.*?<!-- SHIELDS_END -->",
        re.DOTALL,
    )
    new_shields = f"<!-- SHIELDS_START -->\n{shields_content}\n<!-- SHIELDS_END -->"

    if shields_pattern.search(content):
        content = shields_pattern.sub(new_shields, content)
    else:
        h1_pattern = re.compile(r"^(# [^\n]*\n)", re.MULTILINE)
        if h1_pattern.search(content):
            content = h1_pattern.sub(rf"\1\n{new_shields}\n", content, count=1)
        else:
            content = f"{new_shields}\n\n" + content

    # Update test results
    table_pattern = re.compile(
        r"<!-- TEST_RESULTS_START -->.*?<!-- TEST_RESULTS_END -->",
        re.DOTALL,
    )
    new_table = f"<!-- TEST_RESULTS_START -->\n{table_content}\n<!-- TEST_RESULTS_END -->"

    if table_pattern.search(content):
        content = table_pattern.sub(new_table, content)
    else:
        running_tests_pattern = re.compile(r"(## Running the tests)", re.MULTILINE)
        section = f"## Test Results\n\n{new_table}\n\n"
        if running_tests_pattern.search(content):
            content = running_tests_pattern.sub(rf"{section}\1", content, count=1)
        else:
            content = content.rstrip() + f"\n\n## Test Results\n\n{new_table}\n"

    # Update code coverage section if data is available
    if cov_data:
        cov_table_content = generate_coverage_table(cov_data)
        cov_pattern = re.compile(
            r"<!-- COVERAGE_START -->.*?<!-- COVERAGE_END -->",
            re.DOTALL,
        )
        new_cov_block = f"<!-- COVERAGE_START -->\n{cov_table_content}\n<!-- COVERAGE_END -->"

        if cov_pattern.search(content):
            content = cov_pattern.sub(new_cov_block, content)
        else:
            # Place right before ## Roadmap / TODO
            roadmap_pattern = re.compile(r"(## Roadmap / TODO)", re.MULTILINE)
            cov_section = f"## Code Coverage\n\n{new_cov_block}\n\n"
            if roadmap_pattern.search(content):
                content = roadmap_pattern.sub(rf"{cov_section}\1", content, count=1)
            else:
                content = content.rstrip() + f"\n\n## Code Coverage\n\n{new_cov_block}\n"

    readme_path.write_text(content, encoding="utf-8")
    cov_msg = f" (coverage: {cov_data['line_rate']:.1f}%)" if cov_data else ""
    print(f"Successfully updated {readme_path} with {data['passed']}/{data['total']} tests passing{cov_msg}.")


def main():
    parser = argparse.ArgumentParser(description="Update README.md with test results and code coverage.")
    parser.add_argument("xml_path", nargs="?", default="vunit_out/xunit.xml", type=Path, help="Path to xUnit XML report")
    parser.add_argument("--coverage-xml", default=None, type=Path, help="Path to Cobertura coverage XML report")
    parser.add_argument("--readme", default="README.md", type=Path, help="Path to README.md")
    args = parser.parse_args()

    if not args.xml_path.exists():
        print(f"Error: XML report file '{args.xml_path}' not found.", file=sys.stderr)
        sys.exit(1)

    update_readme(args.readme, args.xml_path, cov_path=args.coverage_xml)


if __name__ == "__main__":
    main()
